# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestAadirtarea():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testAadirtarea(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(602, 743)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Tarea de Selenium IDE")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Tarea")
    self.driver.find_element(By.NAME, "title").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "title").send_keys("Tarea de Selenium IDE 2")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
